name: Run integration tests

on:
  push:
    branches: [develop, master]
  pull_request:
    types: [opened,reopened,synchronize]

jobs:
  test-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-environment

      - name: test:integration:coverage
        run: yarn test:integration:coverage
